version: "3.8"

services:
  mysql-server:
    image: registry.cn-hangzhou.aliyuncs.com/chatdg/mysql:5.7.38
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: $INFRAM_PASSWORD
    volumes:
      - $DATA_ROOT_DIR/mysql:/var/lib/mysql
    restart: always
    ports:
      - "$MYSQL_PORT:3306"

  redis-server:
    image: registry.cn-hangzhou.aliyuncs.com/chatdg/redis:5.0.8-debian-10-r24
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: $INFRAM_PASSWORD
    restart: always
    user: root
    volumes:
      - $DATA_ROOT_DIR/redis/data:/bitnami/redis/data
    ports:
      - "$REDIS_PORT:6379"

  nacos-server:
    image: registry.cn-hangzhou.aliyuncs.com/chatdg/nacos-server:v2.2.0
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql-server
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=$INFRAM_PASSWORD
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - $DATA_ROOT_DIR/nacos/standalone-logs/:/home/nacos/logs
    ports:
      - "$NACOS_PORT:8848"
      #- "9848:9848"
    restart: always
    depends_on:
      - mysql-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio-server:
    image: registry.cn-hangzhou.aliyuncs.com/chatdg/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: $INFRAM_PASSWORD
    volumes:
      - ${DATA_ROOT_DIR}/minio:/minio_data
    command: minio server /minio_data --console-address '0.0.0.0:8202'
    restart: always
    ports:
      - "$MINIIO_PORT:9000"
      - "$MINIIO_WEB_PORT:8202"

networks:
  default:
    name: ${NETWORK_NAME}
